apiVersion: v2
name: pl-proxy
description: Helm Chart for the pl-proxy component of API Gateway
type: application
version: 0.1.0
appVersion: "v1"

dependencies:
- name: pl-proxy-dev
  version: 0.1.0
  repository: https://helm.github.io/examples